# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "web3" branch
  push:
    branches: [ "web3" ]
  pull_request:
    branches: [ "web3" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: D3rHase/ssh-command-action@{version}
        with:
          host: ${{secrets.HOST}} # Remote server address / ip - required
          port: ${{secrets.PORT}} # Remote server port -  Default: 22 - optional
          user: ${{secrets.USER}} # Remote server user - required
          private_key: ${{secrets.PRIVATE_KEY}} # Private ssh key registered on the remote server - required
          host_fingerprint: ${{secrets.HOST_FINGERPRINT}} # Public ssh key fingerprint, viewable via ssh-keyscan -H $HOST -p $PORT - optional
          command: echo 'hello world' # Command to be executed - Default: echo 'hello world' - optional
