version: '3'
services:
    Database:
      image: mysql:8.0 #установка mysql
      volumes:
        - /home/lakalam/data_mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=zabbix
        - MYSQL_USER=zabbix
        - MYSQL_PASSWORD=zabbix_pwd
        - MYSQL_ROOT_PASSWORD=root_pwd
      ports:
        - 3306:3306

      #networks:
      #  - zabbix-net
      restart: always
      command:
        --character-set-server=utf8
        --collation-server=utf8_bin
        --default-authentication-plugin=mysql_native_password
      container_name: mysql-server1
    Zabbix_server:
      image:
      volumes:

      container_name: Zabbix_server

    web:
      images:
      volumes:

      container_name: nginx
