version: '3'
services:
    Database:
      image: mysql:8.0 #установка mysql
      volumes:
        - /home/lakalam/zabbix/data_mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=zabbix
        - MYSQL_USER=zabbix
        - MYSQL_PASSWORD=zabbix_pwd
        - MYSQL_ROOT_PASSWORD=root_pwd
      ports:
        - 3306:3306

      #networks: 
      #  - zabbix-net
      restart: always
      command:
        --character-set-server=utf8
        --collation-server=utf8_bin
        --default-authentication-plugin=mysql_native_password
      container_name: zabbix_mysql-server
    Zabbix_server:
      image: zabbix/zabbix-server-mysql:alpine-6.0-latest
      volumes:
        - /home/lakalam/zabbix/zabbix-server:/var/lib/zabbix
        #- /home/lakalam/zabbix/zabbix-server/zabbix_server.conf:/etc/zabbix/zabbix_server.conf:ro
      environment: 
        - DB_SERVER_HOST=zabbix_mysql-server
        - MYSQL_DATABASE=zabbix
        - MYSQL_USER=zabbix
        - MYSQL_PASSWORD=zabbix_pwd
        - MYSQL_ROOT_PASSWORD=root_pwd
        - ZBX_JAVAGATEWAY=zabbix-java-gateway
      #networks:
      #  -  zabbix-net
      ports:
        - 10051:10051
      container_name: zabbix_server
      restart: always
      depends_on: 
        - Database
    web:
      image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
      #volumes:
      #   - /home/lakalam/zabbix/zabbix-nginx:/var/lib/zabbix
      environment:
        - ZBX_SERVER_HOST=zabbix_server
        - DB_SERVER_HOST=zabbix_mysql-server
        - MYSQL_DATABASE=zabbix
        - MYSQL_USER=zabbix
        - MYSQL_PASSWORD=zabbix_pwd
        - MYSQL_ROOT_PASSWORD=root_pwd
      #networks:
      #  - zabbix-net
      ports:
        - 80:8080
      container_name: zabbix_nginx
      restart: always
      depends_on: 
        - Database
        - Zabbix_server
    java-gateway:
      image: zabbix/zabbix-java-gateway:alpine-6.0-latest
      #volumes:
      #  -  
      #networks: 
      #   - zabbix-net
      restart: always
      container_name: zabbix-jagateway
networks: 
  default:
    external:
      name: zabbix-net
