name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DEB01 }}
        username: ${{ secrets.USERNAME_DEB01 }}
        password: ${{ secrets.PASSWORD_DEB01 }}
        port: ${{ secrets.PORT_DEB01 }}
        source: "./index.html"
        target: "./Compose/My_web/html/m.nerpeg.ru/"
