name: CD
on:
 push:
    branches: ["web3"]
 pull_request:
    branches: ["web3"]
jobs:
  build:
   name: Run_hello
   runs-on: ubuntu-latest
   steps:
   - name: run_coomand 
     uses: D3rHase/ssh-command-action@v0.2.2
     with:
      host: ${{secrets.HOST_TS01}}
      port: ${{secrets.PORT_TS01}}
      user: ${{secrets.USERNAME_TS01}}
      private_key: ${{secrets.PRIVATE_KEY_TS01}} # Private ssh key registered on the remote server - required
      #host_fingerprint: ${{secrets.HOST_FINGERPRINT_TS01}} # Public ssh key fingerprint viewable via s sh-keyscan -H $HOST -p $PORT - optional
      command: echo 'hello world'
