name: CD
on:
 push:
    branches: ["web3"]
 pull_request:
    branches: ["web3"]
jobs:
  build:
   name: Run_hello
   runs-on: ubuntu-latest
   steps:
   - name: run_coomand 
     uses: D3rHase/ssh-command-action@v0.2.2
     with:
      host: ${{secrets.HOST_TS01}}
      port: ${{secrets.PORT_TS01}}
      user: ${{secrets.USER_TS01}}
      command: echo 'hello world'
